# Copyright (c) 2023, Oracle and/or its affiliates.
# # Licensed under the Universal Permissive License v1.0 as shown at https://oss.oracle.com/licenses/upl.
#
source "https://rubygems.org"

gem "oj"
gem "json"
gem "fluentd"
gem "fluent-plugin-oci-logging-analytics"
gem "fluent-plugin-concat"
gem "fluent-plugin-rewrite-tag-filter"
gem "fluent-plugin-parser-cri"
gem "fluent-plugin-kubernetes_metadata_filter"
gem "fluent-plugin-kubernetes-objects"
gem "fluent-plugin-oci-logging"
